# Generated by Django 5.0.9 on 2024-10-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
