# Generated by Django 5.0.9 on 2024-10-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='introduction',
        ),
    ]
